### PR TITLE
Fixes compatibility issues with @Injectable in `ng test` unit tests.

### PR DESCRIPTION
**Pull request by albyrock87**
Importing and using ngrx-actions decorators breaks all my angular unit tests using `@Injectable()` decorators.
This is caused by usage of reflect-metadata package, in fact angular is not using this library in [its decorators](https://github.com/angular/angular/blob/master/packages/core/src/util/decorators.ts#L60).

### CODE REVIEW

**Comment by amcdnl** [comment]
Reflect is actually used under the hood in angular. Its just used via core-js ... look at core-js/es7/reflect. We should probably update this to use that.

**Comment by albyrock87** [comment]
Read the comment on the upper row that you indicate to me :)
`If you use AOT (and only Angular decorators), you can remove.`
That means that Angular decorators does not use Reflect.
In fact `@angular/core` does not import `reflect-metadata`. (see its own package.json)

**Comment by amcdnl** [comment]
Oh wow, I missed that. I didn't realize they moved away from reflect. If Angular is ok with this, I'm on board too. Thanks for your explanation and contribution. Happy to bring this in given that info.

**Comment by amcdnl** [comment]
published! 2.1.1

**Comment by albyrock87** [comment]
Thank you very much!

**Comment by albyrock87** [comment]
Thank you very much!

**Pull request merged**
